---
title: "Analisis Android"
author: "Alfonso Salas"
date: '2022-05-18'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Analisis

Se va a realizar un analisis de los datos proporcionados por VirusTotal en forma de JSON. Primero se han de preparar los datos para su analisis, por lo que la primera transfromacion que debemos hacer es de JSON a listas de listas.

## read_json
## Spread_all

```{r }
## Primero leemos los nombres de archivos (Recortados manualmente para que no estalle la funcion)

library(jsonlite)
library(curl)
library(tidyjson)
library(tidyr)
library(dplyr)
library(purrr)
library(tidyverse)
library(rjson)
library(ggplot2)

filenames <- list.files(pattern=".json",recursive = TRUE, path = ".")
filenames

df_total = data.frame()
for (i in 1:183){
  # vector output
  model <- read_json(filenames[i])
  # add vector to a dataframe
  df_total <- rbind(bind_rows(df_total,model  %>%
  spread_all(., recursive = TRUE)))
}


```


A continuación vamos a hacer un analisis de la informacion que nos han compartido desde VirusTotal



```{r}


library(ggplot2)
library(dplyr)


dat <- android %>% mutate(detections = sum(scans$detected = TRUE))

dat <- android %>% select(as.data.frame(size), as.data.frame(positives))

ggplot(df_total,
       aes(x = size,
           y = total)) +
  geom_point() +
  facet_wrap(.~type)

grpSnsdata <- kmeans(df_total[,c("size","total")], centers=3, nstart=10)



```

